name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pipenv pytest pytest-cov
          pip install pipenv
          pipenv install --dev
      - name: Run tests
        run: |
          pipenv run pytest --junitxml=junit/test-results.xml --cov=contract --cov-report=xml --cov-report=html
